### ISSUE TITLE
Problem Hamiltonian append zz gate

### ISSUE THREAD

**Issue by abhishekrajgaria** [rsln-s/IEEE_QW_2020#1]
Since it is e^(-i gamma (-Zi Zj)) = e^(i gamma Zi Zj).

Shouldn't we use  qc.rz(-2*gamma, q2) ?

**Comment by rsln-s** [comment]
@abhishek210 that is correct, based on the current qiskit documentation. However, it doesn't matter all that much: any constant factors can be taken care of by renormalizing gamma. Moreover, the difference between the two is the global phase `exp(0.5i\theta)`, i.e. a global phase, so as far as I can tell this would not affect measurement probabilities...
